import 'package:dvells/pages/model/local_storage.dart';

class StudyRepository extends LocalStorageRepository {
  Map<String, dynamic> studyData = {
    "seongsu": [
      {
        "id": "0",
        "cid": "0",
        "imgUrl": "assets/study1.png",
        "channel": "부캐부클이",
        "category": "자기계발/독서",
        "desc": "매주 1권, 한달 4권 독서 토론 클럽",
        "price": "15000",
        "location": "성수동",
        "favorite": "282",
        "members": "81",
        "rating": "52",
      },
      {
        "id": "1",
        "cid": "1",
        "imgUrl": "assets/study2.png",
        "channel": "스마트스토어러스",
        "category": "재테크/부업",
        "desc": "부업을 꿈꾸는 모두를 위해",
        "price": "10000",
        "location": "망원동",
        "favorite": "112",
        "members": "11",
        "rating": "5",
      },
      {
        "id": "2",
        "cid": "2",
        "imgUrl": "assets/study3.png",
        "channel": "팀 공인전문가",
        "category": "자격증/시험",
        "desc": "공인자격증 따는 스터디",
        "price": "20000",
        "location": "이태원동",
        "favorite": "16",
        "members": "101",
        "rating": "81",
      },
      {
        "id": "3",
        "cid": "3",
        "imgUrl": "assets/study4.png",
        "channel": "1인개발새발",
        "category": "코딩/1인창업",
        "desc": "플러터로 앱만들어요!",
        "price": "25000",
        "location": "청담동",
        "favorite": "791",
        "members": "102",
        "rating": "299",
      },
      {
        "id": "4",
        "cid": "4",
        "imgUrl": "assets/study5.png",
        "channel": "초창패 모임",
        "category": "스타트업/창업",
        "desc": "패기로 뭉친 초기창업가들",
        "price": "10000",
        "location": "역삼동",
        "favorite": "112",
        "members": "21",
        "rating": "101",
      },
      {
        "id": "5",
        "cid": "5",
        "imgUrl": "assets/study6.png",
        "channel": "나이트러너스",
        "category": "자기계발/건강",
        "desc": "밤마다 뛰댕기는 날다람쥐들",
        "price": "5000",
        "location": "반포동",
        "favorite": "92",
        "members": "56",
        "rating": "12",
      }
    ]
  };
}
